# Generated by Django 5.2.1 on 2025-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_tourpackage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
