# Generated by Django 5.2.1 on 2025-05-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_people',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(default='2025-06-01'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
