# Generated by Django 5.2.1 on 2025-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_booking_num_people_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
