# Generated by Django 5.2.1 on 2025-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_tourpackage_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
