# Generated by Django 5.2.1 on 2025-05-16 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_tourpackage_expiry_date_tourpackage_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
